import type { Metadata } from 'next'
import { Providers } from './providers'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavigationBar, Footer } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js + TS + Apollo-Client + GraphQL',
  description: 'Generated by create next app, and created by Mia',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        minWidth: '340px'
      }}>
        <Providers>
          <NavigationBar />
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
